name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Run unit tests
        run: go test ./...

  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Install gocognit
        run: go install github.com/uudashr/gocognit/cmd/gocognit@latest
      - name: Run gocognit
        run: gocognit -over 10 .
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5

  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
